"""section

Revision ID: 3d43c4685911
Revises: c4668656a40d
Create Date: 2021-02-10 18:47:04.072396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d43c4685911'
down_revision = 'c4668656a40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('section', sa.String(length=3), nullable=True))
    op.add_column('course', sa.Column('type1', sa.String(length=40), nullable=True))
    op.add_column('course', sa.Column('type2', sa.String(length=40), nullable=True))
    op.drop_column('course', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('type', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column('course', 'type2')
    op.drop_column('course', 'type1')
    op.drop_column('course', 'section')
    # ### end Alembic commands ###
