"""name not unique

Revision ID: 999d965d922a
Revises: 3d43c4685911
Create Date: 2021-02-10 18:50:55.876936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999d965d922a'
down_revision = '3d43c4685911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'course', ['name'], unique=True)
    # ### end Alembic commands ###
