"""initial migration

Revision ID: c4668656a40d
Revises: 
Create Date: 2021-02-09 21:31:35.491372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4668656a40d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('start1', sa.Integer(), nullable=True),
    sa.Column('end1', sa.Integer(), nullable=True),
    sa.Column('day1', sa.Integer(), nullable=True),
    sa.Column('split_time', sa.Boolean(), nullable=True),
    sa.Column('start2', sa.Integer(), nullable=True),
    sa.Column('end2', sa.Integer(), nullable=True),
    sa.Column('day2', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
